# Generated by Django 3.1.7 on 2021-03-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Стрим активен'),
        ),
        migrations.AddField(
            model_name='stream',
            name='title',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
