# Generated by Django 3.1.7 on 2021-03-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stream', '0004_auto_20210320_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Создано'),
        ),
    ]
