# Generated by Django 3.1.7 on 2021-03-21 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stream', '0007_stream_stream_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Стрим активен'),
        ),
    ]
