# Generated by Django 3.1.7 on 2021-03-21 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stream', '0008_auto_20210321_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='stream_key',
            new_name='streamKey',
        ),
    ]
