# Generated by Django 3.1.7 on 2021-03-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stream', '0009_auto_20210321_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
    ]
