# Generated by Django 3.1.7 on 2021-03-21 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stream', '0010_auto_20210321_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='streamKey',
            field=models.CharField(default='', max_length=250, verbose_name='StreamKey'),
        ),
    ]
