# Generated by Django 3.1.7 on 2021-03-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_auto_20210320_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='goods', verbose_name='Изображение'),
        ),
    ]
