# Generated by Django 3.1.7 on 2021-03-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_goods_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='img',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='logo',
        ),
    ]
