# Generated by Django 3.1.7 on 2021-03-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_auto_20210320_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='cost',
            new_name='price',
        ),
        migrations.AddField(
            model_name='goods',
            name='articul',
            field=models.CharField(default='', max_length=100, verbose_name='Артикул'),
        ),
    ]
