# Generated by Django 3.1.7 on 2021-03-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_shop',
            field=models.BooleanField(blank=True, default=False, verbose_name='Магазин?'),
        ),
    ]
