# Generated by Django 3.1.7 on 2021-03-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210320_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Токен'),
        ),
    ]
